# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16I62AIb1DEHcTpX_2MPt8FXR7ezNuopX
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Salary_Data.csv')

"""loc, iloc,curtosis, squeness, fill NA, quartiles"""

df.head()

df.tail()

df.isnull().sum()

df.dropna(subset = ['Age', 'Years of Experience', 'Salary', 'Education Level'], inplace=True)

df.isnull().sum()

df['Gender'].nunique()

df['Gender'].unique()

print(df['Education Level'].nunique())
print(df['Job Title'].nunique())

print(df['Education Level'].unique())
print(df['Job Title'].unique())

#df=pd.get_dummies(df, columns=['Education Level'], prefix='Education',drop_first=True)

df.head()

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df['New column']=le.fit_transform(df['Education Level'])

df.head()

df['New column'].unique()

df=pd.get_dummies(df, columns=['Gender'], prefix='Gender',drop_first=True)

df['Job']=le.fit_transform(df['Job Title'])

df=df.drop(['Education Level','Job Title'],axis=1)

df.head()

from sklearn.preprocessing import StandardScaler
s=StandardScaler()

data2=s.fit_transform(df)

print(data2)

from sklearn.preprocessing import MinMaxScaler
c=MinMaxScaler()
data3=c.fit_transform(df)
print(data3)